name: image_magick_q8_but_with_working_linux_this_time
description: Dart bindings for ImageMagick C library which is used to edit images.
version: 1.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.3
dev_dependencies:
  ffigen: ^14.0.1
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        dartPluginClass: ImageMagickFFIPlugin
      linux:
        ffiPlugin: true
        dartPluginClass: ImageMagickFFIPlugin
      windows:
        ffiPlugin: true
        dartPluginClass: ImageMagickFFIPlugin